experiment:
  gpu: 1 # Run on GPU
  #                                           #
  # Dataset pre-processing and configuration  #
  #                                           #
  dataset: movielens_small_2018
  data_config:
    strategy: fixed
    train_path: ../../data/dataset/ml_small_2018/splitting/0/subset_train_230.tsv
    test_path: ../../data/dataset/ml_small_2018/splitting/0/test.tsv
    side_information:
      - dataloader: ItemAttributes
        attribute_file: ../../data/dataset/ml_small_2018/processed_data/map.tsv
  top_k: 50
  evaluation:
    cutoffs: [10]
    simple_metrics: [nDCG, Recall, Precision, nDCGRendle2020, HR, F1, MAP, MAR, MRR, ACLT, APLT, ARP, PopREO, PopRSP, ItemCoverage, NumRetrived, UserCoverage, Gini, SEntropy, EFD, EPC]
  #               #
  # Models Setup  #
  #               #
  models:
    UserKNN:
      meta:
        save_recs: True
        save_weights: True
        verbose: True
      neighbors: 80
      similarity: correlation