experiment:
  gpu: 1 # Run on GPU
  #
  # Dataset pre-processing and configuration
  #
  dataset: facebook_book
  data_config:
    strategy: fixed
    train_path: ../../../../data/dataset/facebook_book/trainingset.tsv
    test_path: ../../../../data/dataset/facebook_book/testset.tsv
    side_information:
      - dataloader: ChainedKG
        map: ../../../../data/dataset/facebook_book/MAPS/map.tsv
        properties: ../../../../data/dataset/facebook_book/properties.config
        threshold: 0
        features: ../../../../data/dataset/facebook_book/features.tsv
  top_k: 50
  #
  # Evaluation Setup
  #
  evaluation:
    cutoffs: [10, 20, 50]
    simple_metrics: [nDCG, Recall, Precision, nDCGRendle2020, HR, F1, MAP, MAR, MRR, ACLT, APLT, ARP, PopREO, PopRSP, ItemCoverage, NumRetrived, UserCoverage, Gini, SEntropy, EFD, EPC]
    paired_ttest: True
    wilcoxon_test: True
  print_results_as_triplets: True
  external_models_path: ../external/models/__init__.py
  #
  # Models Setup
  #
  models:
    #
    # Proxy Recommender to compute metrics on ChatGPT rerank
    #
    ProxyRecommender:
      path: ../data/dataset/facebook_book/google_palm/output_EXP_2_no_rerank.tsv